const ROLES = Object.freeze({
  FRESHER: 'FRESHER',
  STARTUP: 'STARTUP',
  ADMIN: 'ADMIN'
});

const APPLICATION_STATUS = Object.freeze({
  APPLIED: 'APPLIED',
  SHORTLISTED: 'SHORTLISTED',
  INTERVIEW: 'INTERVIEW',
  SELECTED: 'SELECTED',
  REJECTED: 'REJECTED'
});

const INVITATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED'
});

const JOB_STATUS = Object.freeze({
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  DRAFT: 'DRAFT'
});

const JOB_VISIBILITY = Object.freeze({
  PUBLIC: 'PUBLIC',
  PRIVATE: 'PRIVATE'
});

const WORK_MODE = Object.freeze({
  REMOTE: 'REMOTE',
  HYBRID: 'HYBRID',
  ON_SITE: 'ON_SITE'
});

const EMPLOYMENT_TYPE = Object.freeze({
  FULL_TIME: 'FULL_TIME',
  PART_TIME: 'PART_TIME',
  INTERNSHIP: 'INTERNSHIP',
  CONTRACT: 'CONTRACT'
});

const NOTIFICATION_TYPE = Object.freeze({
  INVITATION: 'INVITATION',
  APPLICATION_STATUS: 'APPLICATION_STATUS',
  INTERVIEW_SCHEDULED: 'INTERVIEW_SCHEDULED',
  JOB_ALERT: 'JOB_ALERT',
  RECOMMENDATION: 'RECOMMENDATION',
  SYSTEM: 'SYSTEM'
});

const INTERVIEW_TYPE = Object.freeze({
  TECHNICAL: 'TECHNICAL',
  HR: 'HR',
  MANAGERIAL: 'MANAGERIAL',
  CODING: 'CODING',
  FINAL: 'FINAL'
});

const INTERVIEW_STATUS = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  RESCHEDULED: 'RESCHEDULED'
});

const ASSESSMENT_CATEGORY = Object.freeze({
  FRONTEND: 'FRONTEND',
  BACKEND: 'BACKEND',
  FULLSTACK: 'FULLSTACK',
  DATA_SCIENCE: 'DATA_SCIENCE',
  DEVOPS: 'DEVOPS',
  GENERAL_CS: 'GENERAL_CS',
  SOFT_SKILLS: 'SOFT_SKILLS'
});

module.exports = {
  ROLES,
  APPLICATION_STATUS,
  INVITATION_STATUS,
  JOB_STATUS,
  JOB_VISIBILITY,
  WORK_MODE,
  EMPLOYMENT_TYPE,
  NOTIFICATION_TYPE,
  INTERVIEW_TYPE,
  INTERVIEW_STATUS,
  ASSESSMENT_CATEGORY
};
